from epuletek import *

beolvas('legmagasabb.txt')
print(len(epuletek))
print(f'A legmagasabb épület magassága: {legmagasabb()} méter')
legmagasabb = legmagasabb_epulet()
print(f'A legmagasabb épület:')
print(f'\tNeve: {legmagasabb.nev}')
print(f'\tMagasság: {legmagasabb.magassag}')
print(f'\tEpült: {legmagasabb.epult}')
print(f'\tOrszága: {legmagasabb.orszag}')
print(f'\tVáros: {legmagasabb.varos}')
print('---------------------------------------')
legmagasabb_epulet_index = legmagasabb_epulet_index()
print(f'\tNeve: {epuletek[legmagasabb_epulet_index].nev}')
print(f'\tMagasság: {epuletek[legmagasabb_epulet_index].magassag}')
print(f'\tEpült: {epuletek[legmagasabb_epulet_index].epult}')
print(f'\tOrszága: {epuletek[legmagasabb_epulet_index].orszag}')
print(f'\tVáros: {epuletek[legmagasabb_epulet_index].varos}')
print('---------------------------------------')
print('Legmagasabbak épületek:')
for l in legmagasabbak():
    print(f'\tneve: {l.nev}')

print('---------------------------------------')
legmagasabb_francia = legmagasabb_epulet_adott_orszagban('Franciaország')
print('A legmagasabb francia épület:')
print(f'\tNeve: {legmagasabb_francia.nev}')
print(f'\tMagasság: {legmagasabb_francia.magassag}')
print(f'\tEpült: {legmagasabb_francia.epult}')
print(f'\tOrszága: {legmagasabb_francia.orszag}')
print(f'\tVáros: {legmagasabb_francia.varos}')
